parameters:
#    bella_shaye_paypal.example.class: BellaShaye\PaypalBundle\Example

services:
#    bella_shaye_paypal.example:
#        class: %bella_shaye_paypal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
